// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqyKEd0WPVmMCASZfukJwiDDLIi84cLHA',
    appId: '1:141697793892:web:31985054e362d27bc9c471',
    messagingSenderId: '141697793892',
    projectId: 'shop-app-66701',
    authDomain: 'shop-app-66701.firebaseapp.com',
    storageBucket: 'shop-app-66701.appspot.com',
    measurementId: 'G-KKHYGT8DC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNb4eKPfDI0ieGNy3tg-Aq_tKsIwjZvLw',
    appId: '1:141697793892:android:c275a5d709a04356c9c471',
    messagingSenderId: '141697793892',
    projectId: 'shop-app-66701',
    storageBucket: 'shop-app-66701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOBAHEdyXCE0jDK2CjANSEqPk09zJHK0',
    appId: '1:141697793892:ios:e5ec64fcdbb7b45fc9c471',
    messagingSenderId: '141697793892',
    projectId: 'shop-app-66701',
    storageBucket: 'shop-app-66701.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOBAHEdyXCE0jDK2CjANSEqPk09zJHK0',
    appId: '1:141697793892:ios:a896a488ea850c8fc9c471',
    messagingSenderId: '141697793892',
    projectId: 'shop-app-66701',
    storageBucket: 'shop-app-66701.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
